In [4]:
import os
import cv2
import numpy as np
from sklearn.model_selection import train_test_split
from keras.utils import to_categorical
from tensorflow import keras
import tensorflow as tf
from keras.optimizers import Adam
from keras.models import Sequential, load_model, Model
from keras.layers import Input, Conv2D, MaxPooling2D, Flatten, Dense, Dropout
from sklearn.metrics import classification_report, confusion_matrix

In [5]:
DATA_DIR = "data_all"
IMG_SIZE = 128

fruit_classes = ["ananas", "banane", "tomate", "papaye", "non_fruit"]
maturity_classes = ["pas_mur", "mur", "trop_mur"]

X = []
y_fruit = []
y_maturity = []


for fruit in fruit_classes:
    fruit_path = os.path.join(DATA_DIR, fruit)
    if not os.path.isdir(fruit_path):
        continue

    if fruit == "non_fruit":
        files = [f for f in os.listdir(fruit_path) if f.lower().endswith((".jpg", ".jpeg", ".png"))]
        for filename in files:
            img_path = os.path.join(fruit_path, filename)
            img = cv2.imread(img_path)
            if img is None:
                continue
            img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
            img = cv2.resize(img, (IMG_SIZE, IMG_SIZE))
            img = img / 255.0

            X.append(img)
            y_fruit.append(fruit)
            y_maturity.append(3)
        continue

    for subdir in os.listdir(fruit_path):
        subdir_path = os.path.join(fruit_path, subdir)
        if not os.path.isdir(subdir_path):
            continue

        files = [f for f in os.listdir(subdir_path) if f.lower().endswith((".jpg", ".jpeg", ".png"))]
        for filename in files:
            img_path = os.path.join(subdir_path, filename)
            img = cv2.imread(img_path)
            if img is None:
                continue
            img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
            img = cv2.resize(img, (IMG_SIZE, IMG_SIZE))
            img = img / 255.0

            X.append(img)
            y_fruit.append(fruit)

            if subdir in maturity_classes:
                y_maturity.append(maturity_classes.index(subdir))
            else:
                y_maturity.append(3)


X = np.array(X, dtype=np.float32)
fruit_indices = [fruit_classes.index(f) for f in y_fruit]
y_fruit = to_categorical(fruit_indices, num_classes=len(fruit_classes))

y_maturity = to_categorical(y_maturity, num_classes=len(maturity_classes)+1)
maturity_mask = (np.argmax(y_maturity, axis=1) != 3).astype("float32")

X_train, X_test, y_fruit_train, y_fruit_test, y_maturity_train, y_maturity_test, mask_train, mask_test = train_test_split(
    X, y_fruit, y_maturity, maturity_mask, test_size=0.2, random_state=42
)

print("Train :", X_train.shape, y_fruit_train.shape, y_maturity_train.shape)
print("Test  :", X_test.shape, y_fruit_test.shape, y_maturity_test.shape)


Train : (3816, 128, 128, 3) (3816, 5) (3816, 4)
Test  : (955, 128, 128, 3) (955, 5) (955, 4)


In [11]:
from keras.callbacks import ModelCheckpoint

IMG_SIZE = 128
num_fruit_classes = 5
num_maturity_classes = 3


input_layer = Input(shape=(IMG_SIZE, IMG_SIZE, 3))

x = Conv2D(32, (3, 3), activation='relu', padding='same')(input_layer)
x = MaxPooling2D((2, 2))(x)
x = Conv2D(64, (3, 3), activation='relu', padding='same')(x)
x = MaxPooling2D((2, 2))(x)
x = Conv2D(128, (3, 3), activation='relu', padding='same')(x)
x = MaxPooling2D((2, 2))(x)

x = Flatten()(x)
x = Dense(256, activation='relu')(x)
x = Dropout(0.5)(x)

fruit_output = Dense(num_fruit_classes, activation='softmax', name='fruit_output')(x)

maturity_output = Dense(num_maturity_classes + 1, activation='softmax', name='maturity_output')(x)

model = Model(inputs=input_layer, outputs=[fruit_output, maturity_output])

model.compile(
    optimizer=Adam(learning_rate=0.001),
    loss={
        'fruit_output': 'categorical_crossentropy',
        'maturity_output': 'categorical_crossentropy'
    },
    metrics={
        'fruit_output': 'accuracy',
        'maturity_output': 'accuracy'
    }
)

model.summary()

checkpoint = ModelCheckpoint(
    filepath="fruit_maturity_detector.keras",
    monitor="val_loss",
    save_best_only=True,
    mode="min",
    verbose=1
)

history = model.fit(
    X_train,
    {
        'fruit_output': y_fruit_train,
        'maturity_output': y_maturity_train
    },
    validation_data=(
        X_test,
        {
            'fruit_output': y_fruit_test,
            'maturity_output': y_maturity_test
        }
    ),
    epochs=15,
    batch_size=32,
    callbacks=[checkpoint]  
)


# model.save("fruit_maturity_detector.keras")

print("Modèle sauvegardé dans fruit_maturity_detector.keras")


Model: "functional_1"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ input_layer_1       │ (None, 128, 128,  │          0 │ -                 │
│ (InputLayer)        │ 3)                │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv2d_3 (Conv2D)   │ (None, 128, 128,  │        896 │ input_layer_1[0]… │
│                     │ 32)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ max_pooling2d_3     │ (None, 64, 64,    │          0 │ conv2d_3[0][0]    │
│ (MaxPooling2D)      │ 32)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv2d_4 (Conv2D)   │ (None, 64, 64,    │     18,496 │ max_pooling2d_3[… │
│                     │ 64)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ max_pooling2d_4     │ (None, 32, 32,    │          0 │ conv2d_4[0][0]    │
│ (MaxPooling2D)      │ 64)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv2d_5 (Conv2D)   │ (None, 32, 32,    │     73,856 │ max_pooling2d_4[… │
│                     │ 128)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ max_pooling2d_5     │ (None, 16, 16,    │          0 │ conv2d_5[0][0]    │
│ (MaxPooling2D)      │ 128)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ flatten_1 (Flatten) │ (None, 32768)     │          0 │ max_pooling2d_5[… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_1 (Dense)     │ (None, 256)       │  8,388,864 │ flatten_1[0][0]   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dropout_1 (Dropout) │ (None, 256)       │          0 │ dense_1[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ fruit_output        │ (None, 5)         │      1,285 │ dropout_1[0][0]   │
│ (Dense)             │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ maturity_output     │ (None, 4)         │      1,028 │ dropout_1[0][0]   │
│ (Dense)             │                   │            │                   │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 8,484,425 (32.37 MB)

 Trainable params: 8,484,425 (32.37 MB)

 Non-trainable params: 0 (0.00 B)

Epoch 1/15
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 269ms/step - fruit_output_accuracy: 0.8646 - fruit_output_loss: 0.4226 - loss: 1.2508 - maturity_output_accuracy: 0.6317 - maturity_output_loss: 0.8282
Epoch 1: val_loss improved from None to 0.43978, saving model to fruit_maturity_detector.keras
120/120 ━━━━━━━━━━━━━━━━━━━━ 37s 298ms/step - fruit_output_accuracy: 0.9442 - fruit_output_loss: 0.2022 - loss: 0.7800 - maturity_output_accuracy: 0.7655 - maturity_output_loss: 0.5777 - val_fruit_output_accuracy: 0.9906 - val_fruit_output_loss: 0.0468 - val_loss: 0.4398 - val_maturity_output_accuracy: 0.8545 - val_maturity_output_loss: 0.3927
Epoch 2/15
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 270ms/step - fruit_output_accuracy: 0.9826 - fruit_output_loss: 0.0542 - loss: 0.3924 - maturity_output_accuracy: 0.8840 - maturity_output_loss: 0.3382
Epoch 2: val_loss improved from 0.43978 to 0.27330, saving model to fruit_maturity_detector.keras
120/120 ━━━━━━━━━━━━━━━━━━━━ 35s 296ms/step - fruit_output_accuracy: 0.

In [7]:
results = model.evaluate(
    X_test,
    {
        'fruit_output': y_fruit_test,
        'maturity_output': y_maturity_test
    },
    batch_size=32
)

print("Résultats de l'évaluation :", results)


30/30 ━━━━━━━━━━━━━━━━━━━━ 3s 83ms/step - fruit_output_accuracy: 0.9990 - fruit_output_loss: 0.0026 - loss: 0.2196 - maturity_output_accuracy: 0.9330 - maturity_output_loss: 0.2173
Résultats de l'évaluation : [0.2195550799369812, 0.0026040123775601387, 0.2173159420490265, 0.9989528656005859, 0.9329842925071716]


In [8]:
y_fruit_test_labels = np.argmax(y_fruit_test, axis=1)
y_fruit_pred_labels = np.argmax(model.predict(X_test)[0], axis=1)

print(confusion_matrix(y_fruit_test_labels, y_fruit_pred_labels))
print(classification_report(y_fruit_test_labels, y_fruit_pred_labels, target_names=fruit_classes))


30/30 ━━━━━━━━━━━━━━━━━━━━ 3s 84ms/step
[[ 17   0   0   0   0]
 [  0 497   0   0   0]
 [  0   1 400   0   0]
 [  0   0   0  38   0]
 [  0   0   0   0   2]]
              precision    recall  f1-score   support

      ananas       1.00      1.00      1.00        17
      banane       1.00      1.00      1.00       497
      tomate       1.00      1.00      1.00       401
      papaye       1.00      1.00      1.00        38
   non_fruit       1.00      1.00      1.00         2

    accuracy                           1.00       955
   macro avg       1.00      1.00      1.00       955
weighted avg       1.00      1.00      1.00       955



TEST 1

In [9]:
img = cv2.imread("banane_mur.jpg")
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
img = cv2.resize(img, (128, 128))
img = img / 255.0
img = np.expand_dims(img, axis=0)

pred_fruit, pred_maturity = model.predict(img)

fruit_idx = np.argmax(pred_fruit)
maturity_idx = np.argmax(pred_maturity)

print("Fruit prédit :", fruit_classes[fruit_idx])
print("Maturité prédite :", maturity_classes[maturity_idx])


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step
Fruit prédit : banane
Maturité prédite : mur


TEST 2

In [10]:

model_path = "fruit_maturity_detector.keras"
IMG_SIZE = 128

fruit_classes = ["ananas", "banane", "tomate", "papaye", "non_fruit"]
maturity_classes = ["pas_mur", "mur", "trop_mur"]

model = load_model(model_path)

def predict_image(image_path):
    
    img = cv2.imread(image_path)
    if img is None:
        print(f"Erreur : impossible de lire l'image {image_path}")
        return
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    img = cv2.resize(img, (IMG_SIZE, IMG_SIZE))
    img = img / 255.0
    img = np.expand_dims(img, axis=0)

    pred_fruit, pred_maturity = model.predict(img)
    fruit_idx = np.argmax(pred_fruit)
    maturity_idx = np.argmax(pred_maturity)

    if fruit_classes[fruit_idx] == "non_fruit":
        print(f"Image : {image_path} → Ce n'est pas un fruit.")
    else:
        print(f"Image : {image_path} → Fruit : {fruit_classes[fruit_idx]}, Maturité : {maturity_classes[maturity_idx]}")

predict_image("tomate_mur.jpg")
predict_image("banane_mur.jpg")
predict_image("banane_mur2.png")
predict_image("non_fruit3.jpg")
predict_image("non_fruit1.jpg")
predict_image("7_dos.jpg")

predict_image("tomate_mur1.png")
predict_image("papaye_mur.jpg")
predict_image("banane_pas_mur1.png")


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step
Image : tomate_mur.jpg → Fruit : tomate, Maturité : mur
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step
Image : banane_mur.jpg → Fruit : banane, Maturité : pas_mur
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step
Image : banane_mur2.png → Fruit : banane, Maturité : trop_mur
Erreur : impossible de lire l'image non_fruit3.jpg
Erreur : impossible de lire l'image non_fruit1.jpg
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step
Image : 7_dos.jpg → Fruit : ananas, Maturité : mur
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step
Image : tomate_mur1.png → Fruit : tomate, Maturité : trop_mur
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step
Image : papaye_mur.jpg → Fruit : papaye, Maturité : mur
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
Image : banane_pas_mur1.png → Fruit : tomate, Maturité : pas_mur


In [21]:
from ultralytics import YOLO

model = YOLO("yolov8n.pt")
results = model("banane_mur.jpg")
results[0].show()



image 1/1 c:\Users\HP\Desktop\Rendu\Semestre2\C-DAT-900-ABJ-2-1-ecp-14\banane_mur.jpg: 640x640 1 banana, 111.2ms
Speed: 5.7ms preprocess, 111.2ms inference, 1.7ms postprocess per image at shape (1, 3, 640, 640)
